apiVersion: v1
kind: Service
metadata:
  name: awesome-project-svc-node
  labels:
    app: awesome-project
spec:
  ports:
    - protocol: TCP
      port: 9002
      targetPort: 9001
      nodePort: 30003
  type: NodePort
  selector:
    app: awesome-project