apiVersion: v1
kind: Service
metadata:
  name: awesome-project
  labels:
    app: awesome-project
spec:
  ports:
    - protocol: TCP
      port: 9001
      targetPort: 9001
      name: awesome-project
  type: ClusterIP
  selector:
    app: awesome-project